/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define VIALRGB_NO_DIRECT
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define VIAL_KEYBOARD_UID {0x4F, 0xD8, 0x3C, 0x04, 0xFD, 0x4D, 0x6D, 0xBF}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2}
#define VIAL_UNLOCK_COMBO_COLS { 0, 11}
